import os
import logging
from dotenv import load_dotenv
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

# Load environment variables
load_dotenv()

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

# Create FastAPI application
# Swagger UI available at /docs, ReDoc at /redoc (auto-generated by FastAPI)
app = FastAPI(
    title="n8n-Claude Wiki API",
    description="FastAPI application that receives n8n webhooks and processes requests using Claude API with Obsidian wiki context",
    version="1.0.0",
)

# Add CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Import and include routers
from app.routers import webhook_router
app.include_router(webhook_router)


@app.on_event("startup")
async def startup_event():
    """Load Obsidian wiki content on startup"""
    logger.info("Starting up FastAPI application...")
    wiki_path = os.getenv("WIKI_PATH", "./Claude_wiki")
    logger.info(f"Wiki path configured: {wiki_path}")


@app.on_event("shutdown")
async def shutdown_event():
    """Cleanup on shutdown"""
    logger.info("Shutting down FastAPI application...")


@app.get("/health", tags=["health"])
async def health_check():
    """
    Health check endpoint.
    Returns the health status of the application.
    """
    return {"status": "healthy"}


if __name__ == "__main__":
    import uvicorn
    host = os.getenv("HOST", "0.0.0.0")
    port = int(os.getenv("PORT", "8000"))
    uvicorn.run("app.main:app", host=host, port=port, reload=True)
